tasks:
  - name: lib-build
    openMode: split-right
    openIn: right
    command: |
      cd lib
      yarn install
      yarn build
      yarn test
      gp sync-done mybuild
  - name: example-build
    openIn: right
    command: |
      cd exampleapp
      gp sync-await mybuild
      yarn install
      yarn start